# Generated by Django 4.1.2 on 2022-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.PositiveIntegerField(verbose_name=2),
        ),
    ]
