# Generated by Django 4.1.2 on 2022-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artist_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
