# Generated by Django 4.1.2 on 2022-10-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_lyrics_delete_lyric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
    ]
