# Generated by Django 4.1.2 on 2022-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_artist_first_name_remove_artist_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
