# Generated by Django 4.1.2 on 2022-10-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist'),
            preserve_default=False,
        ),
    ]
